// Owner: A. Payments. `clientRef` is generated by the form once, so a double
// click or retry records the payment exactly once (unique index).
import { z } from "zod";
import { zId } from "./common";

export const recordPaymentSchema = z.object({
  invoiceId: zId,
  amount: z.coerce.number().int().positive("Amount must be more than zero"), // paise
  clientRef: z.string().min(8).max(64),
  method: z.enum(["BANK_TRANSFER", "UPI", "CARD", "CASH", "CHEQUE"]).default("BANK_TRANSFER"),
  reference: z.string().trim().max(120).optional(),
  note: z.string().trim().max(500).optional(),
});

export type RecordPaymentInput = z.infer<typeof recordPaymentSchema>;
