// Generates ARCHITECTURE.md from prisma/schema.prisma: a Mermaid ER diagram plus the
// module map. Run `pnpm erd` after every schema change so the diagram never drifts.
import { readFileSync, writeFileSync } from "node:fs";

const schema = readFileSync("prisma/schema.prisma", "utf8");

type Field = { name: string; type: string; optional: boolean; isList: boolean; attrs: string };
type Model = { name: string; table: string; fields: Field[] };

const models: Model[] = [];
const enums = new Set<string>();
for (const m of schema.matchAll(/enum\s+(\w+)\s*{/g)) enums.add(m[1]);

for (const block of schema.matchAll(/model\s+(\w+)\s*{([\s\S]*?)\n}/g)) {
  const [, name, body] = block;
  const table = body.match(/@@map\("(\w+)"\)/)?.[1] ?? name;
  const fields: Field[] = [];
  for (const raw of body.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("//") || line.startsWith("@@")) continue;
    const m = line.match(/^(\w+)\s+(\w+)(\[\])?(\?)?\s*(.*)$/);
    if (!m) continue;
    fields.push({ name: m[1], type: m[2], isList: !!m[3], optional: !!m[4], attrs: m[5] });
  }
  models.push({ name, table, fields });
}
const modelNames = new Set(models.map((m) => m.name));

const groups: [string, string[]][] = [
  ["Identity", ["User", "Session", "CustomerTier", "Customer", "CustomerContact", "PortalSession", "PortalLoginToken"]],
  ["Catalogue", ["ProductCategory", "Product", "PricelistRule", "ProductPairing"]],
  ["Governance", ["ApprovalRule", "RiskConfig", "Counter"]],
  ["Quotation", ["Quotation", "QuotationLine", "ApprovalRequest", "ApprovalStep", "AuditLog"]],
  ["Fulfillment", ["Warehouse", "StockLevel", "StockMove", "FulfillmentPlan", "Shipment", "FulfillmentLine", "FulfillmentPrompt"]],
  ["Billing", ["RecurringPlan", "Subscription", "BillingSchedule", "SubscriptionChange", "Invoice", "InvoiceLine", "CreditNote", "Payment"]],
  ["Portal and health", ["PortalRequest", "DealAlert"]],
];

const lines: string[] = ["erDiagram"];
for (const m of models) {
  lines.push(`  ${m.table} {`);
  for (const f of m.fields) {
    if (modelNames.has(f.type)) continue; // relation fields are drawn as edges
    const t = enums.has(f.type) ? "enum" : f.type.toLowerCase();
    const key = f.attrs.includes("@id") ? " PK" : f.attrs.includes("@unique") ? " UK" : m.fields.some((r) => r.attrs.includes(`fields: [${f.name}]`)) ? " FK" : "";
    lines.push(`    ${t} ${f.name}${key}`);
  }
  lines.push("  }");
}
for (const m of models) {
  for (const f of m.fields) {
    const rel = f.attrs.match(/@relation\((?:"[^"]*",\s*)?fields:\s*\[(\w+)\]/);
    if (!rel || !modelNames.has(f.type)) continue;
    const parent = models.find((p) => p.name === f.type)!;
    const fk = m.fields.find((x) => x.name === rel[1]);
    const card = fk?.optional ? "o|" : "||";
    lines.push(`  ${parent.table} ${card}--o{ ${m.table} : "${rel[1]}"`);
  }
}

const tableCount = models.length;
const groupList = groups.map(([g, ms]) => `- **${g}**: ${ms.filter((x) => modelNames.has(x)).map((x) => models.find((m) => m.name === x)!.table).join(", ")}`).join("\n");

const doc = `# DealFlow360 architecture

Generated by \`pnpm erd\` from \`prisma/schema.prisma\` (${tableCount} tables). Do not edit the diagram by hand.

## How the modules connect

\`\`\`mermaid
flowchart LR
  Auth[Auth and sessions] --> Workspace[Sales workspace: quotation builder]
  Admin[Admin configuration: products, tiers, chains, warehouses, plans] --> Workspace
  Workspace -->|confirm: risk score + routing| Approval[Approval chain]
  Workspace -->|cart contents| Upsell[Upsell ranking from co-purchase history]
  Approval -->|approved| Send[Send to customer]
  Send --> Portal[Customer portal: negotiate and confirm]
  Portal -->|counter above ceiling| Approval
  Portal -->|confirmed| Fulfillment[Warehouse split and reservation]
  Portal -->|confirmed| Billing[One-time and recurring invoices, proration, payments]
  Workspace --> Health[Deal health: stalled, anomaly, slippage]
  Approval --> Audit[(audit_log)]
  Fulfillment --> Audit
  Billing --> Audit
  Portal --> Audit
  Health --> Reports[Reports and exports]
\`\`\`

## Table groups

${groupList}

## Three design decisions

1. **Integer primary keys plus a random public id.** Joins stay small and fast; anything in a URL (quotation, customer, invoice, subscription) uses a 12 character random \`public_id\`, and the portal additionally scopes every query by the customer on the session.
2. **Per-line ceiling = min(tier ceiling, category ceiling).** The risk score checks every line against its own limit (PDF section 10), then blends the worst overage, the value-weighted overage and a margin-floor penalty with weights from \`risk_config\`. Routing picks the longest chain among the \`approval_rule\` rows that fire.
3. **Day-based proration from the real period.** Subscriptions store their actual period dates; a mid-cycle change credits the old quantity and charges the new one for the remaining calendar days, rounded half-up once per component. Money is integer paise everywhere, percentages are integer basis points.

## Entity relationship diagram

\`\`\`mermaid
${lines.join("\n")}
\`\`\`
`;

writeFileSync("ARCHITECTURE.md", doc);
console.log(`ARCHITECTURE.md written: ${tableCount} tables, ${lines.filter((l) => l.includes("--o{")).length} relations`);
